"""add_reasons_column

Revision ID: 0c871e245f8e
Revises: b2663414eed9
Create Date: 2026-02-08 21:33:32.368062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c871e245f8e'
down_revision: Union[str, Sequence[str], None] = 'b2663414eed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reasons', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reasons')
    # ### end Alembic commands ###
