"""fresh_start_with_real_data

Revision ID: b2663414eed9
Revises: dab9e52d7a0b
Create Date: 2026-02-08 05:30:30.198051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2663414eed9'
down_revision: Union[str, Sequence[str], None] = 'dab9e52d7a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance_from_home', sa.Float(), nullable=True),
    sa.Column('distance_from_last_transaction', sa.Float(), nullable=True),
    sa.Column('ratio_to_median_purchase_price', sa.Float(), nullable=True),
    sa.Column('repeat_retailer', sa.Boolean(), nullable=True),
    sa.Column('used_chip', sa.Boolean(), nullable=True),
    sa.Column('used_pin_number', sa.Boolean(), nullable=True),
    sa.Column('online_order', sa.Boolean(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
